Add WalletConnection class to manage wallet connections and interactions
btc-vision/transaction pull request #77
Opened 2024-12-19 19:39 UTC by impredmet

2024-12-28 11:56 UTC, impredmet reviewed
Fixed the conflicts

2024-12-28 11:59 UTC, impredmet reviewed
Bumped version to 1.1.18

2024-12-29 00:41 UTC, BlobMaster41 requested changes

2024-12-29 00:41 UTC, BlobMaster41 commented on src/transaction/browser/extensions/XverseSigner.ts
> +        console.log(callSign);
Remove this.

2024-12-29 00:41 UTC, BlobMaster41 commented on src/transaction/browser/extensions/XverseSigner.ts
> +            [this.p2wpkh]: options[0].toSignInputs?.map((input) => input.index) || [],
Uh? P2wpkh is only segwit.

2024-12-29 00:41 UTC, BlobMaster41 commented on src/transaction/browser/extensions/XverseSigner.ts
> +            [this.p2wpkh]: opts.toSignInputs?.map((input) => input.index) || [],
P2wpkh is only segwit.

2024-12-29 00:41 UTC, BlobMaster41 commented on src/transaction/browser/extensions/XverseSigner.ts
>              toSignPsbts.push(hex);
Why?

2024-12-30 23:30 UTC, impredmet reviewed
Fixed the conflicts

2024-12-30 23:44 UTC, impredmet reviewed
Fixed the export for ContractAddress

2025-01-01 16:51 UTC, impredmet reviewed
Fixed the conflicts

2025-01-01 22:00 UTC, impredmet commented on src/transaction/browser/extensions/XverseSigner.ts
> +        console.log(callSign);
Done.

2025-01-01 22:00 UTC, merged